### PR TITLE
Install sawtooth bin into cli image

### PR DESCRIPTION
**Pull request by pa3ng**
## Proposed change/fix

See title

## Types of changes

What types of changes does this pull request introduce to ConsenSource? _Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (could be a small readme update, documentation contribution, etc.)

## How to run/test

`docker build -t target/consensource-cli:latest .`

`docker run -it target/consensource-cli:latest bash`

`sawtooth keygen`

### CODE REVIEW

**Comment by trevormcdonald** [comment]
I got multiple warnings about package sources being configured multiple times:

```
W: Target Packages (universe/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list:51
W: Target Packages (universe/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list:51
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
The docker image that is built does have `sawtooth` installed but does not have `csrc`, though I can see that the `deb` built with `cargo` is present.

**Comment by trevormcdonald** [comment]
Running `dpkg -i /tmp/consensource-cli*.deb ` manually in the running container does install the package as expected.

**Comment by pa3ng** [comment]
@trevormcdonald sad, had it working on a manual install 🤔  will dig further

**Comment by pa3ng** [comment]
@trevormcdonald should be good now 👍  i don't think we needed the `python3-sawtooth-*` specific packages, just the `sawtooth` package

**Review by adeebahmed — APPROVED** [review]

**Pull request merged**
